queue_rules:
  - update_method: rebase
    name: Dependency Updates
pull_request_rules:
  - name: Automatic merge dependency updates
    description: Merge dependency updates
    conditions:
      - base = master
    actions:
      merge:
        method: rebase
