version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: dockerfile
      args:
        DOCKER_BUILDKIT: 1
    shm_size: '4gb'
    image: miskatonic_server
    deploy:
      resources:
        reservations:
          cpus: '6'
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - .:/usr/src/miskatonic
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8266:8266"
      - "6006:6006"
      - "51047:51047"
    environment:
      - DJANGO_SETTINGS_MODULE=miskatonic.settings
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - RAY_memory_monitor_refresh_ms=0
    depends_on:
      db:
        condition: service_healthy